version: "1"

services:
  web:
    image: httpd
    volumes:
      - ./website:/usr/local/apache2/htdocs
    environment:
      - HOST=0.0.0.0
    ports:
      - 81:81

volumes:
  mysql:
    driver: local
