name: GitHub Actions
run-name: ${{ github.actor }} lance le github action
on: [push]
jobs:
       Explore-GitHub-Actions:
              runs-on: ubuntu-latest
              steps:
                     - run: echo "Let's go test !"
                     - run: echo "key = ${{secrets.SSH_PRIVATE_KEY }}"
                     - name: Deploy to Staging server
                       uses: easingthemes/ssh-deploy@v2.2.11
                       env:
                              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                              ARGS: "-rltgoDzvO"
                              SOURCE: "dist/"
                              REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                              REMOTE_USER: ${{ secrets.REMOTE_USER }}
                              TARGET: "/home/kevin/www/testgit/"
                              EXCLUDE: "/dist/, /node_modules/"
