name: GitHub Actions
run-name: ${{ github.actor }} lance le github action
on: [push]
jobs:
       Explore-GitHub-Actions:
              runs-on: ubuntu-latest
              steps:
                     - run: echo "On tente de se connecter"
                     - name: Deploy to Staging server
                       uses: actions/checkout@v2
                     - name: executing remote ssh commands to deploy
                       uses: appleboy/ssh-action@master
                       with:
                              name: "ssh-var"
                              host: ${{ secrets.HOST }}
                              port: ${{ secrets.PORT }}
                              username: ${{ secrets.USER }}
                              key: ${{ secrets.SSH_PRIVATE_KEY }}
                              passphrase: ${{ secrets.PASS }}
                     - name: "Deploy with rSync"
                       run: ssh ${{ steps.ssh-var.outputs.SERVER }} pwd
