name: first-github-action
on:
       push:
              branches:
                     - main
jobs:
       write-to-console:
              name: Write to console
              runs-on: window-latest
              steps:
                     - run: echo 'Hello world!'
