name: GitHub Actions
run-name: ${{ github.actor }} lance le github action
on: [push]
jobs:
       Explore-GitHub-Actions:
              runs-on: ubuntu-latest
              steps:
                     - run: echo "On tente de se connecter"
                     - name: Deploy to Staging server
                     - uses: actions/checkout@v2
                     - name: rsync deployments
                       uses: burnett01/rsync-deployments@5.2
                       with:
                              switches: -avzr --delete --exclude="" --include="" --filter=""
                              path: src/
                              remote_path: /home/debian/www/testgit
                              remote_host: ${{secrets.HOST}}
                              remote_port: ${{secrets.PORT}}
                              remote_user: ${{secrets.USER}}
                              remote_password: ${{secrets.PASS}}
                              remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
