name: Test de GitHub Actions
run-name: ${{ github.actor }} lance le github action
on:
       push:
              branches:
                     - master

env:
       NODE_VERSION: "12"

jobs:
       build:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@master

                     - name: Set up node
                       uses: actions/setup-node@master
                       with:
                              node-version: ${{ env.NODE_VERSION }}
                              cache: "npm"

                     - name: npm install
                       run: npm install

                     - name: Build
                       run: npm run build

                     - name: create artifact
                       uses: actions/upload-artifact@v1
                       with:
                              name: react-github-actions-build
                              path: build

       deploy:
              runs-on: ubuntu-latest
              needs: build
              steps:
                     - name: Get artifact
                       uses: actions/download-artifact@v1
                       with:
                              name: react-github-actions-build
                              path: ./build

                     - name: Deploy
                       uses: easingthemes/ssh-deploy@v2
                       env:
                              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                              SOURCE: "build"
                              REMOTE_HOST: ${{ secrets.HOST }}
                              REMOTE_USER: ${{ secrets.USER }}
                              REMOTE_PORT: ${{ secrets.PORT }}
                              TARGET: "/home/debianftp/www/"
