name: Test de GitHub Actions
run-name: ${{ github.actor }} lance le github action
on:
       push:
              branches:
                     - master

env:
       NODE_VERSION: "12"

jobs:
       build:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@master

                     - name: Set up node
                       uses: actions/setup-node@master
                       with:
                              node-version: ${{ env.NODE_VERSION }}
                              cache: "npm"

                     - name: npm install
                       run: npm install

                    - name: Build
                      run: npm run build

                    - name: Share artifact inside workflows
                      uses: actions/upload-artifact@v1
                      with:
                        name: react-github-actions-build
                        path: build

