name: GitHub Actions
run-name: ${{ github.actor }} lance le github action
on: [push]
jobs:
       Explore-GitHub-Actions:
              runs-on: ubuntu-latest
              steps:
                     - run: echo "Let's go test !"
                     - run: echo "key = ${{secrets.SSH_PRIVATE_KEY }}"
                     - name: Connect SSH
                       uses: D3rHase/ssh-command-action@v8
