name: Actions Testing
on:
       push:
              branches:
                     - master
jobs:
       write-to-console:
              name: Write to console
              runs-on: windows-latest
              steps:
                     - run: echo 'Hello world!'
                     - uses: actions/checkout@v2
                     - uses: actions/setup-node@v2
                            with:
                            node-version: '14'
                     - name: Install SSH Key
                       uses: shimataro/ssh-key-action@v2
                       with:
                              key: ${{ secrets.SSH_PRIVATE_KEY }}
