name: Deploy on Serve
run-name: ${{ github.actor }} lance le deploiement
on:
       push:
              branches:
                     - master

env:
       NODE_VERSION: "12"
       DIR_ON_SERVER: ./www/

jobs:
       build:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@master

                     - name: FTP
                       uses: SamKirkland/FTP-Deploy-Action@4.3.2
                       with:
                              server: ${{ secrets.HOST_FTP }}
                              username: ${{ secrets.USER_FTP }}
                              password: ${{ secrets.PASS_FTP }}
                              local-dir: ./build/
                              server-dir: ${{ env.DIR_ON_SERVER }}
